language: node_js
node_js:
  - 11
 
install:
  - yarn
  
stages:
  - Build
  
jobs:
  include:
    - stage: Build
      script:
        - CI=false yarn build

deploy:
   edge: true
   provider: anynines
