sudo: required

language: node_js
node_js:
- 13.1.0

before_script:
- openssl aes-256-cbc -K $encrypted_624b4ed64e85_key -iv $encrypted_624b4ed64e85_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
- yarn

stages:
- name: Build

- name: DeployKaraokeTest
  if: branch = cicd AND type=push
  
- name: DeployKaraoke
  if: branch = master AND type=push
  
jobs:
  include:
  - stage: Build
    script:
      - CI=false yarn build
      - ssh -p 22 deploy@dev1.kienthuc24h.com "/bin/mkdir -p /home/deploy/build/karaoke-frontend"
      - rsync -a -e "ssh -p 22" ./ deploy@dev1.kienthuc24h.com:/home/deploy/build/karaoke-frontend/ --delete --exclude="node_modules"

  - stage: DeployKaraokeTest
    script:
      - ssh -p 22 deploy@dev1.kienthuc24h.com "cp -R --remove-destination /home/deploy/build/karaoke-frontend/build/* /var/www/karaoketest.kienthuc24h.com"

  - stage: DeployKaraoke
    script:
      - ssh -p 22 deploy@dev1.kienthuc24h.com "cp -R --remove-destination /home/deploy/build/karaoke-frontend/build/* /var/www/karaoke.kienthuc24h.com"
