sudo: required

language: node_js
node_js:
- 11

before_script:
  - export COMMIT_TIME=$(date +%Y%m%dT%H%M)




# install:
# - yarn



stages:
- Build
jobs:
  include:
  - stage: Build
    script:
      - ls
    # - CI=false yarn build

# after_success:
# - ping dev1.kienthuc24h.com

addons:
  ssh_known_hosts: dev1.kienthuc24h.com

before_install:
- ls
- openssl aes-256-cbc -K $encrypted_624b4ed64e85_key -iv $encrypted_624b4ed64e85_iv -in deploy_rsa.enc -out deploy_rsa -d
- ll
# - chmod 600 deploy_rsa
# - ssh-add deploy_rsa

deploy: 
  provider: script
  script:
    - ssh -p 22 deploy@dev1.kienthuc24h.com "/bin/mkdir -p /home/deploy/commit"
    - rsync -a -e "ssh -p 22" build/ deploy@dev1.kienthuc24h.com:/home/deploy/commit/${COMMIT_TIME} --delete
  on:
    all_branches: true
